" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2019 Jan 26
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

set nobackup

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" augroup cursorline
"	autocmd!
"	autocmd VimEnter,WinEnter,BufWinEnter * setlocal cursorline
"	autocmd WinLeave * setlocal nocursorline
" augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

" Copy and paste
map <C-v> "*P
vnoremap <C-c> "*y :let @+=@*<CR>

" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Misc settings
set number
set laststatus=2
" set t_Co=256
set termguicolors
set splitbelow splitright
set cursorline
set cursorcolumn

"if &term =~ '256color'
	" disable Background Color Erase (BCE) so that color schemes
	" render properly when inside 256-color tmux and GNU screen.
"	set t_ut=
"endif

colo kveld
syntax on
set background=dark

" Quick-scope
let g:qs_highlight_on_keys = ['f', 'F']
hi QuickScopePrimary cterm=underline ctermfg=155
hi QuickScopeSecondary cterm=underline ctermfg=81

" NerdTree
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeQuitOnOpen = 1
nmap <F5> :NERDTreeToggle<CR>
nmap <F6> :NERDTreeFind<CR>

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#wordcount#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='base16_default'

" Colors
hi LineNr ctermfg=242 guifg=#6c6c6c
hi CursorColumn ctermbg=234 cterm=bold guibg=#1c1c1c
hi CursorLine ctermbg=234 cterm=bold guibg=#1c1c1c
hi CursorLineNr ctermfg=248 ctermbg=234 cterm=bold guifg=#a8a8a8 guibg=#1c1c1c
hi StatusLine cterm=bold ctermbg=235 ctermfg=246 guibg=#262626 guifg=#949494
hi VertSplit cterm=bold ctermbg=235 ctermfg=238 guibg=#262626 guifg=#444444
hi WildMenu term=standout cterm=bold ctermbg=Green ctermfg=Black guibg=#a1b56c guifg=Black
