" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2019 Jan 26
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

set nobackup

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" augroup cursorline
"	autocmd!
"	autocmd VimEnter,WinEnter,BufWinEnter * setlocal cursorline
"	autocmd WinLeave * setlocal nocursorline
" augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

" Copy and paste
map <C-v> "*P
vnoremap <C-c> "*y :let @+=@*<CR>

set number
set laststatus=2
set t_Co=256

if &term =~ '256color'
	" disable Background Color Erase (BCE) so that color schemes
	" render properly when inside 256-color tmux and GNU screen.
	set t_ut=
endif

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#wordcount#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='badwolf'

colo koehler
syntax on
set background=dark
set cursorline
hi LineNr ctermfg=242
hi CursorColumn ctermbg=234 cterm=bold
hi CursorLine ctermbg=234 cterm=bold
hi CursorLineNr ctermfg=248 ctermbg=234 cterm=bold
hi StatusLine cterm=bold ctermbg=235 ctermfg=246
hi WildMenu term=standout cterm=bold ctermbg=Green ctermfg=Black
