#! /bin/sh

sxhkd &
picom -b &
nitrogen --restore &
polybar -c $HOME/.config/polybar/bspwm-config top &
tilda -h &

bspc monitor -d term web chat code music VI VII VIII

bspc config border_width        2
bspc config window_gap          4
bspc config focused_border_color \#e39a7b
bspc config normal_border_color \#5b5b5b
#bspc config -d ^2 window_gap    0
#bspc config -d ^2 border_width  0

bspc config focus_follows_pointer true
bspc config top_padding 21
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config single_monocle	true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Vivaldi-stable desktop='^2' follow=on
bspc rule -a VirtualBox desktop='^8' state=floating follow=on
bspc rule -a "VirtualBox Manager" state=floating
#bspc rule -a VirtualBoxVM state=floating
bspc rule -a Guake state=floating
bspc rule -a Tilda state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Galculator state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

